# Generated by Django 5.1.3 on 2025-02-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('genres', models.CharField(max_length=25)),
                ('length', models.IntegerField()),
                ('author', models.ManyToManyField(related_name='authored_books', to='books.author')),
            ],
        ),
    ]
