# Generated by Django 5.1.3 on 2025-02-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Chat Room', 'verbose_name_plural': 'Chat Rooms'},
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='participants',
            new_name='members',
        ),
    ]
