# Generated by Django 5.1.3 on 2025-02-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionquestion',
            options={'verbose_name': 'Discussion Question', 'verbose_name_plural': 'Discussion Questions'},
        ),
    ]
