# Generated by Django 5.1.3 on 2025-02-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_clubs', to='books.book')),
                ('bookclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_books', to='bookclubs.bookclub')),
            ],
        ),
    ]
