# Generated by Django 5.1.3 on 2025-02-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubs', '0002_pastbook'),
        ('users', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookclub',
            options={'verbose_name': 'Book Club', 'verbose_name_plural': 'Book Clubs'},
        ),
        migrations.AddField(
            model_name='bookclub',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookclubs_created', to='users.userprofile'),
        ),
    ]
